MODEL:
  BACKBONE: "resnet50"
  MESH_ON: True
  CHECKPOINT: ""
  MESH_HEAD:
    NAME: "SphereInitHead"
    NUM_STAGES: 3
    NUM_GRAPH_CONVS: 3
    GRAPH_CONV_DIM: 128
    GRAPH_CONV_INIT: "normal"
    GT_NUM_SAMPLES: 5000
    PRED_NUM_SAMPLES: 5000
    CHAMFER_LOSS_WEIGHT: 1.0
    NORMALS_LOSS_WEIGHT: 0.0
    EDGE_LOSS_WEIGHT: 0.2
    ICO_SPHERE_LEVEL: 4
DATASETS:
  NAME: "shapenet"
SOLVER:
  BATCH_SIZE: 64 # 32
  BATCH_SIZE_EVAL: 8
  NUM_EPOCHS: 25
  BASE_LR: 0.0001
  OPTIMIZER: "adam"
  LR_SCHEDULER_NAME: "constant"
  LOGGING_PERIOD: 50
